image: node:6

dev-deploy:
  type: deploy
  script:
  - apt-get update
  - apt-get install ruby-dev
  - gem install dpl
  - yarn install
  - yarn build
  - dpl --provider=heroku --app=fra-platform --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
