image: node:6

stages:
  - build
  - deploy

build:
  stage: build
  script:
  - apt-get update
  - apt-get install --assume-yes rubygems
  - gem install dpl
  - yarn install
  - yarn test
  - yarn build

deploy_staging:
  stage: deploy
  script:
  - dpl --provider=heroku --app=$HEROKU_STAGING_APP_NAME --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
  environment:
    name: staging
    url: https://dev-fra-platform.herokuapp.com/

deploy_production:
  stage: deploy
  script:
  - dpl --provider=heroku --app=$HEROKU_PRODUCTION_APP_NAME --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - master
  when: manual
  environment:
    name: production
    url: https://fra-platform.herokuapp.com/

